export const INCREASE = 'INCREASE';
export const DECREASE = 'DECREASE';
export const INCREASE_STORE = 'INCREASE_STORE';
export const DECREASE_STORE = 'DECREASE_STORE';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';

